#!/bin/bash
# Starts a secure tunnel to expose the local Flask app to the internet.
# Required: ./temp_tunnel_key (generated by the agent)

echo "Starting Remote Tunnel..."
echo "Your app will be available at a https://...lhr.life URL shown below."
echo "Press Ctrl+C to stop."
echo "---------------------------------------------------"

ssh -i ./temp_tunnel_key -o StrictHostKeyChecking=no -R 80:localhost:5000 localhost.run
